server:
  port: 9080
spring:
  application:
    name: 'one_click_library_management'
  datasource:
    url: jdbc:mysql://localhost:3306/one_click
    username: 'root'
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'mmohammad.rizwan@gmail.com'
    password: 'nyhz npzm ystw dugw'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: true

logging:
  level:
    org:
      springframework:
        mail: DEBUG
        web:
          client:
            RestTemplate: DEBUG

base_url: http://localhost:9080/api/v1/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 60000 # 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days

